language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t afigienas321/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true afigienas321/docker-react npm run test